Controllers/PaymentPayStackController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Payments.Paystack.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using PayStack.Net;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;

namespace Nop.Plugin.Payments.Paystack.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class PaymentPaystackController : BasePaymentController
    {
        #region Fields

        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly IPermissionService _permissionService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IWebHelper _webHelper;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor
        public PaymentPaystackController(
          IOrderProcessingService orderProcessingService,
          IOrderService orderService,
          IPermissionService permissionService,
          ILocalizationService localizationService,
          INotificationService notificationService,
          ISettingService settingService,
          IStoreContext storeContext,
          IWebHelper webHelper,
          IWorkContext workContext)
        {
            _orderProcessingService = orderProcessingService;
            _orderService = orderService;
            _permissionService = permissionService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _settingService = settingService;
            _storeContext = storeContext;
            _webHelper = webHelper;
            _workContext = workContext;
        }
        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            int storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var PaystackPaymentSettings = _settingService.LoadSetting<PaystackPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                SecretKey = PaystackPaymentSettings.SecretKey,
                AdditionalFee = PaystackPaymentSettings.AdditionalFee,
                EnableAdditionalFee = PaystackPaymentSettings.EnableAdditionalFee,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope <= 0)
                return View("~/Plugins/Payments.Paystack/Views/Configure.cshtml", model);

            model.SecretKey_OverrideForStore = _settingService.SettingExists(PaystackPaymentSettings, x => x.SecretKey, storeScope);
            model.AdditionalFee_OverrideForStore = _settingService.SettingExists(PaystackPaymentSettings, x => x.AdditionalFee, storeScope);
            model.EnableAdditionalFee_OverrideForStore = _settingService.SettingExists(PaystackPaymentSettings, x => x.EnableAdditionalFee, storeScope);
            return View("~/Plugins/Payments.Paystack/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            // load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var PaystackPaymentSettings = _settingService.LoadSetting<PaystackPaymentSettings>(storeScope);

            PaystackPaymentSettings.SecretKey = model.SecretKey;
            PaystackPaymentSettings.AdditionalFee = model.AdditionalFee;
            PaystackPaymentSettings.EnableAdditionalFee = model.EnableAdditionalFee;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(PaystackPaymentSettings, x => x.SecretKey, model.SecretKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(PaystackPaymentSettings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(PaystackPaymentSettings, x => x.EnableAdditionalFee, model.EnableAdditionalFee_OverrideForStore, storeScope, false);
            
            //now clear settings cache
            _settingService.ClearCache();

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        public IActionResult Callback()
        {
            try
            {
                PaystackPaymentSettings standardPaymentSettings = _settingService.LoadSetting<PaystackPaymentSettings>(_storeContext.ActiveStoreScopeConfiguration);

                string str = Request.QueryString.ToString();
                NameValueCollection queryString = HttpUtility.ParseQueryString(str);
                TransactionVerifyResponse transactionVerifyResponse = new PayStackApi(standardPaymentSettings.SecretKey).Transactions.Verify(queryString.Get("reference"));

                if (transactionVerifyResponse.Status && transactionVerifyResponse.Data.Status == "success")
                {
                    Metadata metadata = transactionVerifyResponse.Data.Metadata;
                    string empty1 = string.Empty;
                    string empty2 = string.Empty;
                    foreach (KeyValuePair<string, object> keyValuePair in (Dictionary<string, object>)metadata)
                    {
                        string key = keyValuePair.Key;
                        if (keyValuePair.Key == "customOrderNumber")
                            empty2 = keyValuePair.Value.ToString();
                        if (keyValuePair.Key == "orderGuid")
                            empty1 = keyValuePair.Value.ToString();
                    }

                    Order orderByGuid = _orderService.GetOrderByGuid(Guid.Parse(empty1));

                    if (this._orderProcessingService.CanMarkOrderAsPaid(orderByGuid))
                    {
                        orderByGuid.AuthorizationTransactionId = transactionVerifyResponse.Data.Reference;
                        this._orderService.UpdateOrder(orderByGuid);
                        this._orderProcessingService.MarkOrderAsPaid(orderByGuid);
                    }

                    return (IActionResult)((ControllerBase)this).RedirectToRoute("CheckoutCompleted", (object)new
                    {
                        orderId = ((BaseEntity)orderByGuid).Id
                    });
                }
                else if (transactionVerifyResponse.Status && transactionVerifyResponse.Data.Status == "failed" || (!transactionVerifyResponse.Status || !(transactionVerifyResponse.Data.Status == "abandoned")))
                {
                    var order = _orderService.SearchOrders(_storeContext.CurrentStore.Id,
                        customerId: _workContext.CurrentCustomer.Id, pageSize: 1).FirstOrDefault();
                    return RedirectToRoute("OrderDetails", new { orderId = order.Id });
                }
    
                return (IActionResult)((ControllerBase)this).Content(string.Empty);
            }
            catch (Exception ex)
            {
                return (IActionResult)((ControllerBase)this).Content(string.Empty);
            }
        }

        public IActionResult CancelOrder()
        {
            var order = _orderService.SearchOrders(_storeContext.CurrentStore.Id,
                customerId: _workContext.CurrentCustomer.Id, pageSize: 1).FirstOrDefault();

            if (order != null)
                return RedirectToRoute("OrderDetails", new { orderId = order.Id });

            return RedirectToRoute("Homepage");
        }

        #endregion
    }
}

Views/Configure.cshtml
@model Nop.Plugin.Payments.Paystack.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentPaystack" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>
                    Paystack is one of the payment gateway's used in Nigeria.
                </h3>
                <ol>
                    <li>You will need a Paystack Merchant account. If you don't already have one, you can sign up here: https://Paystack.com/</li>
                    <li>Sign in to your Paystack Portal. Go to Setting, API Keys & Webhooks to obtain your secret live or test secret key.</li>
                </ol>

                <br>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecretKey_OverrideForStore" asp-input="SecretKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecretKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecretKey" asp-required="true" asp-value="@Model.SecretKey" />
                        <span asp-validation-for="SecretKey"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableAdditionalFee_OverrideForStore" asp-input="EnableAdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableAdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="EnableAdditionalFee" />
                        <span asp-validation-for="EnableAdditionalFee"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.Paystack.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>